Hw02 express
EvgeniyTIR/nodejs-homework-rest-api pull request #1
Opened 2022-11-10 23:00 UTC by EvgeniyTIR

Check homework please

2022-11-11 18:46 UTC, Eastvarga commented on middlewares/validation.js
> +		return res.status(400).json({ message: "missing required name field!" });
Валідація повертає помилку валідаційну, тому краще Вам її використовувати як message корректно обробивши.
Вам треба білше розібратися з валідацією

2022-11-11 18:46 UTC, Eastvarga commented on middlewares/validation.js
> +	console.log(result);
не треба залишати консолі у готовому коді

2022-11-11 18:47 UTC, Eastvarga commented on middlware/validation.js
> +const validation = (req, res, next) => {
А для чого дублювання коду? Це дивно, Вам треба прибрати зайве

2022-11-11 18:48 UTC, Eastvarga commented on models/contacts.js
> +	console.log(JSON.parse(data));
теж зайва консоль

2022-11-11 18:58 UTC, Eastvarga commented on models/contacts.js
> +		return false;
дивна структура - у Вас це єдина з функцій оперування данними, котра чомусь повертає булеве значеня. Старайтеся у схожих логіках дотримуватись одноманітності, інакше це буде гармидир. 
const removeContact = async (contactId) => {
	const data = await listContacts();
	let removedContact;
	const updatedContacts = data.filter((item) => {
		if (item.id === contactId) {
			removedContact = item;
		
		}
		return item.id !== contactId;
	});
	await fs.writeFile(contactsDB, JSON.stringify(updatedContacts));
	return removedContact;
}; 
Так мабуть доречніше буде, чи не так?

2022-11-11 19:05 UTC, Eastvarga commented on models/contacts.js
> +	fs.writeFile(contactsDB, JSON.stringify(data));
Не дуже гарно мутувати елемент масиву. По-перше це скрита логіка, яку в подальшому важко відстежувати.
По-друге це можна зробити через метод масиву map((elem)=>{if(elem.id===contactId){ return {...elem,...body} return elem}})  якось так

2022-11-11 19:08 UTC, Eastvarga commented on routes/api/contacts.js
> +		res.status(200).json({ message: "success", code: 200, contacts });
json( contacts) краще не використовувати зайві поля ищ цей метод віключно для тіла відповіді, код статусу Ви засетили до нього вже .status(200)

2022-11-11 19:10 UTC, Eastvarga commented on routes/api/contacts.js
> +		if (!name || !email || !phone) {
Навіщо перевірки після валідації? Чому валідація не виконує цю перевірку? Вам треба додати до валідації методи required для усіх полів

2022-11-11 19:13 UTC, Eastvarga commented on routes/api/contacts.js
> +		if (name || email || phone) {
зовсім давна конструкція. Цей метод потребує усіх полів отже валідація це повинна перевірити та якщо код дійшов до цього моменту ця контсрукція не потрібна, бо всі поля повинні буди

2022-11-11 19:14 UTC, Eastvarga requested changes
Є зауваження, треба їх усунути

2022-11-13 09:33 UTC, Eastvarga commented on middlewares/validation.js
> +		return res.status(400).json({ message: "missing required name field" });
Є певна логіка валідаторів. 
Кожен повертає помилку відповідно схемі, тому достатньо відстежувати чи повертає валідатор помилку після валідації, та якщо повертає використовувати її у відповіді 
const { error }= schema.validate(req.body);
if(error) {

return res.status(400).json({ message: error.message }); //тут самі розбиретесь
}

2022-11-13 09:35 UTC, Eastvarga commented on middlewares/validation.js
> +			.max(20),
є метод optional() для вказання не обов'язкових полей

2022-11-13 09:36 UTC, Eastvarga commented on middlewares/validation.js
> +		return res.status(400).json({ message: "missing fields" });
це теж буде у помилці валідатора, Ваше завдання коректно налаштувати сам валідатор

2022-11-13 09:37 UTC, Eastvarga commented on models/contacts.js
> +	return data;
чому апдейт повертає список замість створенного елементу?

2022-11-13 09:41 UTC, Eastvarga commented on models/contacts.js
> +	return contact;
Ви не маєте розуміня що робить метод мап - він повертає масив в которому елементи це те що повертає калбек функція вказана у ньому- тобто в нашому разі це той самий масив де оновлений буде лише потрібний нам елемент, якщо він буде існувати!
тому - некоректне ім'я змінної, не коректе значення повертає функція (має бути оновлений елемент а не масив

2022-11-13 09:43 UTC, Eastvarga commented on routes/api/contacts.js
> +		res.status(200).json({ message: "success", contacts });
res.status(200).json({ message: "success", contacts }); message - зовсім зайве, достатньо повертати самі contacts  у тілі відповіді

2022-11-13 09:43 UTC, Eastvarga commented on routes/api/contacts.js
> +		res.status(200).json({ message: "success", contact });
теж саме

2022-11-13 09:43 UTC, Eastvarga commented on routes/api/contacts.js
> +		res.status(201).json({ message: "success", contact });
теж саме

2022-11-13 09:44 UTC, Eastvarga requested changes
Є не виправлені зауваження, додав коментарі

2022-11-13 12:21 UTC, EvgeniyTIR commented on middlewares/validation.js
> +		return res.status(400).json({ message: "missing required name field" });
Я розумiю, але в завданнi менi потрiбно вивести конкретный меседж, якщо обовьязковi поля не заповненi:
Если в body нет каких-то обязательных полей, возвращает json с ключом {"message": "missing required name field"} и статусом 400
Тобто всi попереднi перевiрки робилися для того щоб вивести цей потрiбний меседж, як зроби це по iншому я не знаю.

2022-11-13 13:47 UTC, Eastvarga commented on middlewares/validation.js
> +		return res.status(400).json({ message: "missing required name field" });
"missing required [key name] field" так, мабуть зрозуміліше буде?
це меседж валідації. Якщо я вірно пам'ятаю текст помилки можна задавати параметром у валідаторі, але це не критично=) зовсів. Критично це розуміння структури коду та того, що за що повинно відповідати, цьому Ви повинні навчатися. Тому Вам з логікою валідації треба розібратись.

2022-11-13 16:34 UTC, Eastvarga commented on middlewares/validation.js
> +		return res.status(400).json({ message: "missing required name field" });
https://stackoverflow.com/questions/48720942/node-js-joi-how-to-display-a-custom-error-messages
Вам потрібно також вчитися шукати інформацію, інколи треба вміння коректно сформулювати запит пошуку, і це також залежить від теоретичної бази та самого досвіду пошуку. Сам постійно вдосконалююсь у цьому =)

2022-11-13 16:37 UTC, Eastvarga commented on models/contacts.js
> +	return contact;
Не бачу змін, чому віддаєте масив контактів?

2022-11-13 16:38 UTC, Eastvarga requested changes
НЕе коректна відповідь на оновлення елементу

2022-11-14 18:11 UTC, Eastvarga approved these changes

2022-11-14 22:53 UTC, merged