Hw03 mongodb
EvgeniyTIR/nodejs-homework-rest-api pull request #2
Opened 2022-11-15 17:23 UTC by EvgeniyTIR

Перевiрте будьласка

2022-11-15 18:32 UTC, Eastvarga commented on controllers/controllers.js
> +	res.json({ contacts });
Зайва вкладеність, та чому ви використовуєте різні назви данних елементу? тоді вже використовуйте загальну назву поля data

2022-11-15 18:40 UTC, Eastvarga commented on controllers/controllers.js
> +		req.body.favorite = false;
оце цікава конструкція яка призводить до неможливості виконати операцію створення без зазначення поля favorite, а що сказано у ДЗ?

2022-11-15 18:42 UTC, Eastvarga commented on controllers/controllers.js
> +		return res.json({ updatedContact });
Чи користувались Ви postman для перевірки того як працює Ваш код? Та чи відповідає він критеріям ДЗ?

2022-11-15 18:44 UTC, Eastvarga commented on db/conection.js
> +		await mongoose.connect(process.env.MONGO_URL, {
Зазвичай не використовують у коді відразу змунну з процесу. Їх вказують у окремому файлі у об'єкті, а потім цей об'єкт імпортують де треба, та з нього беруть потрібну змінну

2022-11-15 18:46 UTC, Eastvarga commented on middlewares/validation.js
> +		.length(4)
У PUT об'єкті для апдейту не може бути опціональних полей - вони всі обов'язкові мають бути. Перевірте, що таке PUT та PATCH методи

2022-11-15 18:47 UTC, Eastvarga commented on middlewares/validation.js
> +const validationFavorite = (req, res, next) => {
валідуватись має лише поле favorite інші поля зайві, уважно читайте ТЗ

2022-11-15 18:49 UTC, Eastvarga commented on server.js
>  app.listen(3000, () => {
краще винести змінну порту у конфіг файл

2022-11-15 18:49 UTC, Eastvarga requested changes
Є декілька зауважень

2022-11-15 20:20 UTC, EvgeniyTIR commented on controllers/controllers.js
> +		req.body.favorite = false;
Тут не розумiю в чому помилка, наче все вiрно, додаэ поле  favorite = folse

2022-11-15 21:44 UTC, Eastvarga commented on controllers/controllers.js
> +		req.body.favorite = false;
Умовою є те, що у запиті на створення  може не бути поля, favorite, але в такому разі у базі пзапишеться значення false для цього поля. Да й ваша консирукція дещо дика
const { favorite= false,... user} = req.body
Всезначно простіше можна зробити

2022-11-15 21:49 UTC, EvgeniyTIR commented on controllers/controllers.js
> +		req.body.favorite = false;
А все зрозумiв, там в классi вказано вже

2022-11-17 14:46 UTC, Eastvarga commented on controllers/controllers.js
> +	res.json({ contact });
res.json( contact ); ось вираз повертає об'єкт!!

2022-11-17 14:47 UTC, Eastvarga commented on controllers/controllers.js
> +	res.json({ contact });
теж саме

2022-11-17 14:48 UTC, Eastvarga commented on controllers/controllers.js
> +	res.json({ newContact });
Чо му тут об'єкт знаходиться у полі newContact  відповіді? res.status(201).json(newContact); це коректний запис

2022-11-17 14:50 UTC, Eastvarga commented on controllers/controllers.js
> +		return res.json({ changedContact });
чому тут об'єкт відповіді знаходиться у полі changedContact відповіді?  res.status(200).json(changedContact );

2022-11-17 14:50 UTC, Eastvarga commented on controllers/controllers.js
> +		return res.json({ updatedContact });
return res.json({ updatedContact }); теж саме

2022-11-17 14:52 UTC, Eastvarga commented on helpers/envImport.js
> +const PORT = process.env.PORT_ENV;
PORT можна сетити для розробки дефолтним значенням
const config ={
PORT:  process.env.PORT_ENV|| 3000,
MONGO_URL = process.env.MONGO_URL_ENV,
}

2022-11-17 14:59 UTC, Eastvarga approved these changes
Добре, але є зауваження стосовно формату відповідей

2022-11-17 14:59 UTC, merged