Hw06 email
EvgeniyTIR/nodejs-homework-rest-api pull request #5
Opened 2022-11-29 00:18 UTC by EvgeniyTIR

2022-11-29 19:31 UTC, Eastvarga requested changes
Багато зауважень, слід доопрацювати

2022-11-29 19:31 UTC, Eastvarga commented on controllers/authController.js
> +const { PORT } = require("../helpers/envImport");
Не плодіть строки використовуйте деструктивне присвоєння
const { SENDGRID_API_KEY, PORT, SECRET  } = require("../helpers/envImport");
або імпортуйте повний об'єкт
const config = require("../helpers/envImport");

2022-11-29 19:31 UTC, Eastvarga commented on controllers/authController.js
> -	const user = new User({ email, password });
Треба перевіряти чи дублюється юзер при реєстрації. 
Де ця перевірка з відповідною реакцією?

2022-11-29 19:31 UTC, Eastvarga commented on controllers/authController.js
> +		const msg = {
чому не виділили відправку пошти у окремий сервіс, котрий імпортуєте та використовуєте лише один його метод для відправлення пошти?

2022-11-29 19:31 UTC, Eastvarga commented on controllers/authController.js
>  			throw new Conflict("Email in use");
Не вірна логіка перевірки дублювання юзера.

2022-11-29 19:31 UTC, Eastvarga commented on controllers/authController.js
> +	const user = await User.findOne({ email, verify: true });
Невірно.
Не знайден юзер -це один кейс, а не веріфіковано пошту - другий, вони повинні відрізнятися

2022-11-29 19:31 UTC, Eastvarga commented on controllers/authController.js
> +	if (user === null) {
невірна логіка, якщо немає юзера з таким токеном, то невірний або не валідний токен, з чого Ви уявили ніби-то юзер тоді вже авторізован?

2022-11-29 19:31 UTC, Eastvarga commented on controllers/authController.js
> +	const msg = {
У Вас дублюється купа строк, зробіть окремий модуль для саме відправлення пошти

2022-11-29 19:31 UTC, Eastvarga commented on controllers/authController.js
> +	const alreadyVerifedUser = await User.findOne({ email, verify: true });
Де це ви таке бачили? Навіщо двічи запитувати БД, якщо можна один раз витягди юзера та співставити його значення verify тим паче що воно буль?

2022-11-29 19:31 UTC, Eastvarga commented on controllers/authController.js
> +		message: "Check you email, verification messege already send",
Не вдалий текст.

2022-11-29 19:31 UTC, Eastvarga commented on helpers/envImport.js
> +const SENDGRID_API_KEY = process.env.SENDGRID;
але відправник, це теж конфігураційний параметр чому Ви його не додали сюди?

2022-11-30 03:35 UTC, EvgeniyTIR commented on controllers/authController.js
> -	const user = new User({ email, password });
email: {
		type: String,
		required: [true, "Email is required"],
		unique: true,
	}
Перевірка на унікальність юзера  обробляется у схемі

2022-11-30 03:45 UTC, EvgeniyTIR commented on controllers/authController.js
>  			throw new Conflict("Email in use");
Тут не розумію

2022-11-30 19:20 UTC, Eastvarga commented on controllers/authController.js
>  			throw new Conflict("Email in use");
Логіка повинна бути послідовною
1 отримали креди юзера
2 знайшли чи є вже такий юзер
3 якщо є відповідаєм помилкою "Email in use"
4 немає тоді створюєм юзера. 
Ви же використовуєте помилку запису в БД як ориєнтир ніби то існування юзера.
Ви не повинні створювати запити до БД котрі спричинюють помилки - це не нормально як для БД так і для управління БД 
Сервер- це одна сутність - БД інша. (сервер-бд) Вони не повинні спілкуватись між собою помилками!!

2022-11-30 19:29 UTC, Eastvarga approved these changes

2022-11-30 19:29 UTC, merged

2022-11-30 21:56 UTC, EvgeniyTIR commented on controllers/authController.js
>  			throw new Conflict("Email in use");
Зрозуміло, дякую)